name: Deploy to server
on:
  workflow_run:
    workflows: [ "Build to build branch" ]
    branches: [ build ]
    types:
      - completed

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest # ä½¿ç”¨æœ€æ–°çš„ Ubuntu ç³»ç»Ÿä½œä¸ºç¼–è¯‘éƒ¨ç½²çš„ç¯å¢ƒ
    steps:
      - name: Checkout codes ğŸ›
        uses: actions/checkout@v2
        with:
          persist-credentials: false


      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-avz --delete"
          SOURCE: './' # æœ¬åˆ†æ”¯çš„ç›®å½•
          REMOTE_HOST: '8.142.126.113' # ä½ çš„é˜¿é‡Œäº‘å…¬ç½‘åœ°å€
          REMOTE_USER: 'root' # é˜¿é‡Œäº‘ç™»å½•åé»˜è®¤ä¸º root ç”¨æˆ·ï¼Œå¹¶ä¸”æ‰€åœ¨æ–‡ä»¶å¤¹ä¸º root
          TARGET: /root/vue3-cms # æ‰“åŒ…åçš„ dist æ–‡ä»¶å¤¹å°†æ”¾åœ¨ /root/vue3-cms
