name: Vue3-cms CI/CD
on:
  push:
    branches:
      - master
jobs:
  cicd:
    name: Build and deploy
    runs-on: ubuntu-latest # ä½¿ç”¨æœ€æ–°çš„ Ubuntu ç³»ç»Ÿä½œä¸ºç¼–è¯‘éƒ¨ç½²çš„ç¯å¢ƒ
    steps:
      - name: Checkout codes ğŸ›
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      # è®¾ç½® node è¿è¡Œç¯å¢ƒ
      - name: Setup node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '14.x'
      # è®¾ç½®ç¼“å­˜ä¾èµ–ï¼ŒåŠ å¿«ä¸‹æ¬¡å®‰è£…ä¾èµ–çš„é€Ÿåº¦
      - name: Cache node modules
        uses: actions/cache@v2.1.3
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-node-${{ hashFiles('**/yarn.lock') }}

      - name: Install and Build ğŸ”§
        run: |
          yarn install
          yarn build


#      - name: Deploy
#        uses: JamesIves/github-pages-deploy-action@releases/v3
#        with:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
#          BRANCH: build
#          FOLDER: dist

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          ARGS: "-avz --delete"
          SOURCE: './dist' #
          REMOTE_HOST: '8.142.126.113' # ä½ çš„é˜¿é‡Œäº‘å…¬ç½‘åœ°å€
          REMOTE_USER: 'root' # é˜¿é‡Œäº‘ç™»å½•åé»˜è®¤ä¸º root ç”¨æˆ·ï¼Œå¹¶ä¸”æ‰€åœ¨æ–‡ä»¶å¤¹ä¸º root
          TARGET: /root/vue3-cms # æ‰“åŒ…åçš„ dist æ–‡ä»¶å¤¹å°†æ”¾åœ¨ /root/vue3-cms
